New website examples for pie() and spy()
JuliaPlots/Makie.jl pull request #1641
Opened 2022-02-04 11:42 UTC by kimkroener

# Description

I noticed that there are three plotting functions that do not have examples on the website (see #1639). 
Therefore I created two new sites, for the `pie()` and `spy()` function, an example for `timeseries()` is still missing. 

For the pie example I also added some more information about the attributes as it is done for example for the [arrow function](https://makie.juliaplots.org/stable/examples/plotting_functions/arrows/#example_12707894566346229771) because they were not that clear for me in the beginning. 

Would it make sense to add  this description in the [pie docstring](https://github.com/JuliaPlots/Makie.jl/blob/78820311c9b45347f0937caf8b31a25bbc27dd73/src/basic_recipes/pie.jl)? 

I tested the examples with CairoMakie in VS Code as well as with GLMakie in the REPL. 

Please give me feedback if I did everything as its intended as this is my first time contributing :) 

## Type of change

Delete options that do not apply:
- [x] Improvement of the Documentation

## Checklist

- [ ] Added an entry in NEWS.md (for new features and breaking changes)
- [x] Added or changed relevant sections in the documentation
- [ ] Added unit tests for new algorithms, conversion methods, etc.
- [ ] Added reference image tests for new plotting functions, recipes, visual options, etc.

2022-02-04 17:11 UTC, kimkroener commented
I think the build-and-deploy action for the documentation is stuck again, is this something caused by my files?

2022-02-04 17:33 UTC, SimonDanisch commented
No, other PRs are also getting stuck  :(

2022-02-07 08:50 UTC, SimonDanisch commented
Thank you, those are great addition to the docs :) 
@jkrumbiegel, do you want to add anything before we merge this?

2022-02-07 12:40 UTC, jkrumbiegel commented
What is the easiest way to let this actually build a preview page? Then I could take a look at the visual output

2022-02-07 12:52 UTC, kimkroener commented
You can see the generated plots in #1639

2022-02-07 16:00 UTC, jkrumbiegel commented
retriggered this to build artifact

2022-02-07 17:14 UTC, jkrumbiegel requested changes
Thank you! I only have a couple of small suggestions

2022-02-07 23:39 UTC, kimkroener commented
Thanks for the feedback, its really appreciated. The doc pages as as build artifacts are great :+1:

2022-02-10 13:53 UTC, jkrumbiegel approved these changes

2022-02-11 12:46 UTC, merged