Allow weights in statistical recipes
JuliaPlots/Makie.jl pull request #1816
Opened 2022-04-12 13:27 UTC by greimel

Add the keyword `weights` to `boxplot`, `density`, `hist`, `violin`.

## `density`

![image](https://user-images.githubusercontent.com/6280307/162971899-5dbbdfe9-7229-4730-9d39-ff7a719cdb43.png)

```julia
let
	N = 100_000
	x = rand(Uniform(-2, 2), N)
	
	w = pdf.(Normal(), x)

	fig = Figure()
	density(fig[1,1], x)
	density(fig[1,2], x, weights = w)

	fig
end
```

## `violin`
![image](https://user-images.githubusercontent.com/6280307/162972588-d9e75a72-7ec0-4989-a328-dbb76d939cda.png)

```julia
let
	N = 100_000
	x = rand(1:3, N)
	y = rand(Uniform(-1, 5), N)
	
	w = pdf.(Normal(), x .- y)

	fig = Figure()

	violin(fig[1,1], x, y)
	violin(fig[1,2], x, y, weights = w)

	fig
end
```

## `boxplot`
![image](https://user-images.githubusercontent.com/6280307/162972535-0dcc431c-8a76-43ac-a826-9613be4da777.png)

```julia
let
	N = 100_000
	x = rand(1:3, N)
	y = rand(Uniform(-1, 5), N)
	
	w = pdf.(Normal(), x .- y)

	fig = Figure()

	boxplot(fig[1,1], x, y)
	boxplot(fig[1,2], x, y, weights = w)

	fig
end
```

## `hist`
![image](https://user-images.githubusercontent.com/6280307/162972381-eeacb326-f290-4d37-8f19-4798ad0b7678.png)
```julia
let
	N = 100_000
	x = rand(Uniform(-5, 5), N)
	
	w = pdf.(Normal(), x)

	fig = Figure()
	hist(fig[1,1], x)
	hist(fig[1,2], x, weights = w)

	fig
end
```

2022-04-19 10:41 UTC, greimel commented
Friendly bump 😃 

The added functionality generalizes what `AlgebraOfGraphics.density()` and `AlgebraOfGraphics.histogram()` can already do. (e.g. `data(df) * mapping(:y, weights = :wgts) * density() |> draw`)

@piever, since you have written most of the code that this PR touches – would you mind reviewing it if you find some time?

2022-04-20 12:55 UTC, piever requested changes

2022-04-20 12:55 UTC, piever commented on src/stats/violin.jl
> +- `weights`: vector of statistical weights (length of data). By default, each observation has weight 1.
```suggestion
- `weights`: vector of statistical weights (length of data). By default, each observation has weight `1`.
```

2022-04-20 12:55 UTC, piever commented on src/stats/violin.jl
> +                (w === automatic ? NamedTuple() : (weights = StatsBase.weights(view(w, idxs)),))...
We should probably add a utility function to filter out `automatic` keywords, but that should be done separately.

2022-04-20 12:55 UTC, piever commented on src/stats/boxplot.jl
> +- `weights`: vector of statistical weights (length of data). By default, each observation has weight 1.
```suggestion
- `weights`: vector of statistical weights (length of data). By default, each observation has weight `1`.
```

2022-04-20 13:02 UTC, piever commented
Nice! Looks good to me (just left two tiny formatting comments).

I have a minor doubt as to whether we should call `StatsBase.weights` indiscriminately, or instead not call it when the user passes a `StatsBase.AbstractWeight` object. I have no idea whether the various subtypes of `AbstractWeight` make any difference here. I suspect not, so probably it's fine to leave as is.

2022-04-22 08:29 UTC, greimel commented
I've applied your suggestions, thanks for the review!

2022-04-22 12:18 UTC, piever approved these changes

2022-04-22 12:25 UTC, SimonDanisch commented
Great!
There is still an error in the docs:
```
┌ Franklin Warning: in <examples/plotting_functions/violin.md>
│ There was an error of type 'ArgumentError' when running a code block.
│ Checking the output files '/home/runner/work/Makie.jl/Makie.jl/docs/__site/assets/examples/plotting_functions/violin/code/output/example_figure.(out|res)'
│ might be helpful to understand and solve the issue.
│ 
│ Relevant pointers:
│ - evaluation of Julia code blocks: https://franklinjl.org/code/
│ 
│ Details:
│ ArgumentError: Package Distributions not found in current path:
│ - Run `import Pkg; Pkg.add("Distributions")` to install the Distributions package.
```
Can you add that to the docs project?

2022-04-28 12:43 UTC, greimel commented
Done! I hadn't realized that the docs are actually built for non-member contributors these days. That's great news!

2022-05-01 13:08 UTC, greimel commented
I would like to use this for a lecture in about a week.

If it's not too much of a hassle for you, I'd appreciate this being merged and tagged before May 8.

If you don't plan a new tag soon, please let me know and I'll adjust my material accordingly

2022-05-03 08:46 UTC, merged

2022-05-03 09:16 UTC, SimonDanisch commented
I'll try to release a new version!

2022-05-03 14:27 UTC, SimonDanisch commented
Would a breaking version work for you as well?

2022-05-03 14:29 UTC, greimel commented
that's fine, thanks for asking!