Fix DataInspector hover over NaN values
JuliaPlots/Makie.jl pull request #2151
Opened 2022-07-19 03:50 UTC by MariusDrulea

# Description

Fixes https://github.com/JuliaPlots/Makie.jl/issues/1714

Add a description of your PR here.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

2022-07-19 03:58 UTC, MariusDrulea commented
I have tested the change in the PR with the following sample code. Works as expected.
```
using GLMakie

##
x = rand(100, 100)
x[20:60, :] .= NaN
x2 = 100 * rand(100, 100)
x2[40:end, :] .= NaN


##
fig, ax, plot_obj = image(rotr90(x), interpolate=false)
image!(rotr90(x2), interpolate=false, colormap=(:jet1, 0.5))
DataInspector(fig)


##
screen = display(fig)                  
wait(screen)

##
```

2022-07-19 09:29 UTC, ffreyer requested changes
Thanks for the fix. We can merge this after fixing the comment/return value.

2022-07-19 09:29 UTC, ffreyer commented on src/interaction/inspector.jl
> +        return false
This should still return true. In this case getting processed means that there is a `show_data` method that decided what to do with a hovered plot.

2022-07-20 14:29 UTC, ffreyer approved these changes

2022-07-20 14:32 UTC, merged